apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - args:
        - bundle
        - exec
        - rails
        - s
        - -p
        - "3000"
        - -b
        - 0.0.0.0
        image: yannissm/kubernetes-compose-rails:latest
        name: web
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /myapp
          name: web-claim0
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bin/rake db:migrate RAILS_ENV=development"]
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
