apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    app: web
status:
  loadBalancer: {}
